parameters:
  - name: app_name
    type: string
    displayName: 'App Name'
    default: cch
  - name: capability
    type: string
    displayName: 'Capability'
    default: tax
  - name: environment
    type: string
    displayName: 'Environment'
    default: uaf

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  bkstrgrg: 'TF-Backend-RG'
  bkstrg: 'tfdemobackend'
  bkcontainer: 'tax-tfstate'
  bkstrgkey: 'sequence.tfstate:prd'

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $jsonPath = "$(System.DefaultWorkingDirectory)/data/web_deploy_tax_sequence_dev.json"
                $jsonContent = Get-Content $jsonPath -Raw | ConvertFrom-Json
                $jsonContent.deployment.app_name = "$(app_name)"
                $jsonContent.deployment.capability = "$(capability)"
                $jsonContent.deployment.environment = "$(environment)"
                $jsonContent.deployment.web_tier.count = $count
                $jsonContent.deployment.web_tier.recommended_instance_type = $recommended_instance_type
                $updatedJsonContent = $jsonContent | ConvertTo-Json -Depth 10
                Set-Content $jsonPath $updatedJsonContent
            
          - task: TerraformTaskV3@3
            displayName: 'Initialize Terraform'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ADODEVSPN'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
          
          - task: TerraformTaskV3@3
            displayName: 'Validate Terraform'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              
  - stage: tfdeploy
    condition: succeeded('tfvalidate')
    dependsOn: tfvalidate
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $jsonPath = "$(System.DefaultWorkingDirectory)/data/web_deploy_tax_sequence_dev.json"
                $jsonContent = Get-Content $jsonPath -Raw | ConvertFrom-Json
                $jsonContent.deployment.app_name = "$(app_name)"
                $jsonContent.deployment.capability = "$(capability)"
                $jsonContent.deployment.environment = "$(environment)"
                $jsonContent.deployment.web_tier.count = $count
                $jsonContent.deployment.web_tier.recommended_instance_type = $recommended_instance_type
                $updatedJsonContent = $jsonContent | ConvertTo-Json -Depth 10
                Set-Content $jsonPath $updatedJsonContent

          - task: TerraformTaskV3@3
            displayName: 'Initialize Terraform'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'ADODEVSPN'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'

          - task: TerraformTaskV3@3
            displayName: 'Plan Terraform'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'ADODEVSPN'

          - task: TerraformTaskV3@3
            displayName: 'Apply Terraform'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'ADODEVSPN'
